version: '3.7'

services:
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared-net
  mysqldb:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:lib
      - MYSQL_PASSWORD:root
    networks:
      - shared-net
    volumes:
      - ./mysql/data:/backup